apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-job-bert"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      imagePullPolicy: Always
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: <username>/pytorch_dist_bert:latest
              # For CPU "--accelerator", "ddp_cpu"
              args: [
                "--checkpoint_dir", "/model/checkpoint", 
                "--model_save_path", "/model/model_path", 
                "--gpus", "-1", 
                "--accelerator", "ddp", 
                "--num_nodes", "2"
                ]
              ports:
              - containerPort: 24456
                name: pytorchjob-port
              resources:
                limits:
                    nvidia.com/gpu: 1 # requesting 1 GPU
    Worker:
      replicas: 1
      imagePullPolicy: Always
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers: 
            - name: pytorch
              image: <username>/pytorch_dist_bert:latest
              # For CPU "--accelerator", "ddp_cpu"
              args: [
                "--checkpoint_dir", "/model/checkpoint", 
                "--model_save_path", "/model/model_path", 
                "--gpus", "-1", 
                "--accelerator", "ddp", 
                "--num_nodes", "2"
                ]
              ports:
              - containerPort: 24456
                name: pytorchjob-port
              resources:
                limits:
                    nvidia.com/gpu: 1 # requesting 1 GPU
